language: python

matrix:
  fast_finish: true
  include:
    - python: '3.12'
      dist: bionic
    - python: '3.11'
      dist: bionic
    - python:  '3.10'
      dist:  bionic
    - python:  '3.9'
      dist:  bionic
    - python:  '3.8'
      dist:  bionic
    - python:  '3.7'
      dist:  bionic
    - python:  'nightly'
      dist:  bionic
    - python:  '3.11-dev'
      dist:  bionic
    - python:  '3.10-dev'
      dist:  bionic
    - python:  '3.9-dev'
      dist:  bionic
    - python:  '3.8-dev'
      dist:  bionic
    - python:  '3.7-dev'
      dist:  bionic

before_install:
  - pip install coverage
script: coverage run -m pytest
after_success:
  - bash <(curl -s https://codecov.io/bash)
