language: python

matrix:
  fast_finish: true
  include:
    - python:  'pypy3'
    - python:  '3.10.0'
    - python:  '3.10.1'
    - python:  '3.10.2'
    - python:  '3.10'
    - python:  '3.10'
      dist:  bionic
    - python:  '3.9'
    - python:  '3.9'
      dist:  bionic
    - python:  '3.8'
    - python:  '3.7'
    - python:  'nightly'
    - python:  '3.11-dev'
    - python:  '3.10-dev'
    - python:  '3.9-dev'
    - python:  '3.8-dev'
    - python:  '3.7-dev'

before_install:
  - pip install coverage
script: coverage run -m pytest
after_success:
  - bash <(curl -s https://codecov.io/bash)
