name: Upload Python Package and Run Tests

on:
  release:
    types: [created]
  pull_request:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    - name: Install App Dependencies
      run: poetry install --no-interaction --no-root
    - name: Run tests
      run: |
        poetry run pytest
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: publish
      if: github.event_name == 'release'
      shell: bash
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
        poetry publish --build --no-interaction
